apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      # Hard Rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                # Schedules the pod only on nodes in the us-east-1d or us-east-1b zones
                values:
                  - us-east-1d
                  - us-east-1b
      # Soft Rule
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - roboshop
        - weight: 10
          preference:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - amazon
                  

                
  
